name: react CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: yarn install
      run: yarn

    - name: Prettier & Lint
      run: yarn fix

    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v1.5.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}